In [72]:
#import tensorflow as tf
import numpy as np
#import pandas as pd
#import matplotlib.pyplot as plt
import numba as nb
import sys

In [73]:
np.set_printoptions(threshold=sys.maxsize)

In [3]:
import cProfile

In [67]:
# entradas
# numero de vaos em x
vX = 300
# distancia dos vaos em x
dX = 5.25
# número de vãos em y
vY = 5
# distancia dos vaos em y
dY = 7.25
# numero pavimentos
vZ = 7
 # distancia piso a piso
dZ = 3.25

In [68]:
# variáveis auxiliares
#nos da base em x e y
NxBase = vX +1
NyBase = vY +1

# nos nos pavimentos em x e y
Nx2 = vX*2 +1
Ny2 = vY*2 +1

#total de nos no modelo
Npts = (Nx2)*(Ny2)*(vZ) + ( NxBase * NyBase )

In [69]:
mat = np.arange(0,Npts, 1, dtype=np.int32 )

In [65]:
@nb.vectorize(["float32(int32, float32, float)"], target='parallel')
def coordX(M, NxB, NyB):
    if M <  (NxB*NyB):
        return  (M % NxB)*(dX)
    else:
        return  ((M - NxB*NyB) % Nx2)*(dX/2)
    
@nb.vectorize(["float32(int32)"], target='parallel')
def coordY(M):
    if M <  (NxBase*NyBase):
        return  ((M % (NxBase*NyBase))//NxBase)*(dY)
    else:
        return  (((M - NxBase*NyBase) % (Nx2*Ny2))//Nx2)*(dY/2)

@nb.vectorize(["float32(int32)"], target='parallel')
def coordZ(M):
    if M <  (NxBase*NyBase):
        return  0.0
    else:
        return  (((M - NxBase*NyBase) // (Nx2*Ny2)) + 1)*(dZ)

In [74]:
cX = coordX(mat, NxBase)
cY = coordY(mat)
cZ = coordZ(mat)
print( '\ncoord X\n', cX , '\nCoord Y\n', cY, '\nCoord Z\n', cZ)


coord X
 [   0.       5.25    10.5     15.75    21.      26.25    31.5     36.75
   42.      47.25    52.5     57.75    63.      68.25    73.5     78.75
   84.      89.25    94.5     99.75   105.     110.25   115.5    120.75
  126.     131.25   136.5    141.75   147.     152.25   157.5    162.75
  168.     173.25   178.5    183.75   189.     194.25   199.5    204.75
  210.     215.25   220.5    225.75   231.     236.25   241.5    246.75
  252.     257.25   262.5    267.75   273.     278.25   283.5    288.75
  294.     299.25   304.5    309.75   315.     320.25   325.5    330.75
  336.     341.25   346.5    351.75   357.     362.25   367.5    372.75
  378.     383.25   388.5    393.75   399.     404.25   409.5    414.75
  420.     425.25   430.5    435.75   441.     446.25   451.5    456.75
  462.     467.25   472.5    477.75   483.     488.25   493.5    498.75
  504.     509.25   514.5    519.75   525.     530.25   535.5    540.75
  546.     551.25   556.5    561.75   567.     572.25 

 [ 0.     0.     0.     0.     7.25   7.25   7.25   7.25  14.5   14.5
 14.5   14.5   21.75  21.75  21.75  21.75  29.    29.    29.    29.
 36.25  36.25  36.25  36.25   0.     0.     0.     0.     0.     0.
  0.     3.625  3.625  3.625  3.625  3.625  3.625  3.625  7.25   7.25
  7.25   7.25   7.25   7.25   7.25  10.875 10.875 10.875 10.875 10.875
 10.875 10.875 14.5   14.5   14.5   14.5   14.5   14.5   14.5   18.125
 18.125 18.125 18.125 18.125 18.125 18.125 21.75  21.75  21.75  21.75
 21.75  21.75  21.75  25.375 25.375 25.375 25.375 25.375 25.375 25.375
 29.    29.    29.    29.    29.    29.    29.    32.625 32.625 32.625
 32.625 32.625 32.625 32.625 36.25  36.25  36.25  36.25  36.25  36.25
 36.25   0.     0.     0.     0.     0.     0.     0.     3.625  3.625
  3.625  3.625  3.625  3.625  3.625  7.25   7.25   7.25   7.25   7.25
  7.25   7.25  10.875 10.875 10.875 10.875 10.875 10.875 10.875 14.5
 14.5   14.5   14.5   14.5   14.5   14.5   18.125 18.125 18.125 18.125
 18.125 18.125 18.1

 [   0.      0.      0.      0.      0.      0.      0.      0.      0.
    0.      0.      0.      0.      0.      0.      0.      0.      0.
    0.      0.      0.      0.      0.      0.      3.25    3.25    3.25
    3.25    3.25    3.25    3.25    3.25    3.25    3.25    3.25    3.25
    3.25    3.25    3.25    3.25    3.25    3.25    3.25    3.25    3.25
    3.25    3.25    3.25    3.25    3.25    3.25    3.25    3.25    3.25
    3.25    3.25    3.25    3.25    3.25    3.25    3.25    3.25    3.25
    3.25    3.25    3.25    3.25    3.25    3.25    3.25    3.25    3.25
    3.25    3.25    3.25    3.25    3.25    3.25    3.25    3.25    3.25
    3.25    3.25    3.25    3.25    3.25    3.25    3.25    3.25    3.25
    3.25    3.25    3.25    3.25    3.25    3.25    3.25    3.25    3.25
    3.25    3.25    6.5     6.5     6.5     6.5     6.5     6.5     6.5
    6.5     6.5     6.5     6.5     6.5     6.5     6.5     6.5     6.5
    6.5     6.5     6.5     6.5     6.5     6.5     6.5 

In [44]:
matA = mat[NxBase*NyBase::].reshape(vZ, Ny2, Nx2)

In [45]:
matA

array([[[  15351,   15352,   15353, ...,   15949,   15950,   15951],
        [  15952,   15953,   15954, ...,   16550,   16551,   16552],
        [  16553,   16554,   16555, ...,   17151,   17152,   17153],
        ...,
        [  74249,   74250,   74251, ...,   74847,   74848,   74849],
        [  74850,   74851,   74852, ...,   75448,   75449,   75450],
        [  75451,   75452,   75453, ...,   76049,   76050,   76051]],

       [[  76052,   76053,   76054, ...,   76650,   76651,   76652],
        [  76653,   76654,   76655, ...,   77251,   77252,   77253],
        [  77254,   77255,   77256, ...,   77852,   77853,   77854],
        ...,
        [ 134950,  134951,  134952, ...,  135548,  135549,  135550],
        [ 135551,  135552,  135553, ...,  136149,  136150,  136151],
        [ 136152,  136153,  136154, ...,  136750,  136751,  136752]],

       [[ 136753,  136754,  136755, ...,  137351,  137352,  137353],
        [ 137354,  137355,  137356, ...,  137952,  137953,  137954],
    

In [46]:
matXI = matA[::,::2,:-1:]
matXI

array([[[  15351,   15352,   15353, ...,   15948,   15949,   15950],
        [  16553,   16554,   16555, ...,   17150,   17151,   17152],
        [  17755,   17756,   17757, ...,   18352,   18353,   18354],
        ...,
        [  73047,   73048,   73049, ...,   73644,   73645,   73646],
        [  74249,   74250,   74251, ...,   74846,   74847,   74848],
        [  75451,   75452,   75453, ...,   76048,   76049,   76050]],

       [[  76052,   76053,   76054, ...,   76649,   76650,   76651],
        [  77254,   77255,   77256, ...,   77851,   77852,   77853],
        [  78456,   78457,   78458, ...,   79053,   79054,   79055],
        ...,
        [ 133748,  133749,  133750, ...,  134345,  134346,  134347],
        [ 134950,  134951,  134952, ...,  135547,  135548,  135549],
        [ 136152,  136153,  136154, ...,  136749,  136750,  136751]],

       [[ 136753,  136754,  136755, ...,  137350,  137351,  137352],
        [ 137955,  137956,  137957, ...,  138552,  138553,  138554],
    

In [47]:
matXF = matA[::,::2,1::]
matXF

array([[[  15352,   15353,   15354, ...,   15949,   15950,   15951],
        [  16554,   16555,   16556, ...,   17151,   17152,   17153],
        [  17756,   17757,   17758, ...,   18353,   18354,   18355],
        ...,
        [  73048,   73049,   73050, ...,   73645,   73646,   73647],
        [  74250,   74251,   74252, ...,   74847,   74848,   74849],
        [  75452,   75453,   75454, ...,   76049,   76050,   76051]],

       [[  76053,   76054,   76055, ...,   76650,   76651,   76652],
        [  77255,   77256,   77257, ...,   77852,   77853,   77854],
        [  78457,   78458,   78459, ...,   79054,   79055,   79056],
        ...,
        [ 133749,  133750,  133751, ...,  134346,  134347,  134348],
        [ 134951,  134952,  134953, ...,  135548,  135549,  135550],
        [ 136153,  136154,  136155, ...,  136750,  136751,  136752]],

       [[ 136754,  136755,  136756, ...,  137351,  137352,  137353],
        [ 137956,  137957,  137958, ...,  138553,  138554,  138555],
    

In [48]:
matYI = matA[::,:-1:,::2]
matYI

array([[[  15351,   15353,   15355, ...,   15947,   15949,   15951],
        [  15952,   15954,   15956, ...,   16548,   16550,   16552],
        [  16553,   16555,   16557, ...,   17149,   17151,   17153],
        ...,
        [  73648,   73650,   73652, ...,   74244,   74246,   74248],
        [  74249,   74251,   74253, ...,   74845,   74847,   74849],
        [  74850,   74852,   74854, ...,   75446,   75448,   75450]],

       [[  76052,   76054,   76056, ...,   76648,   76650,   76652],
        [  76653,   76655,   76657, ...,   77249,   77251,   77253],
        [  77254,   77256,   77258, ...,   77850,   77852,   77854],
        ...,
        [ 134349,  134351,  134353, ...,  134945,  134947,  134949],
        [ 134950,  134952,  134954, ...,  135546,  135548,  135550],
        [ 135551,  135553,  135555, ...,  136147,  136149,  136151]],

       [[ 136753,  136755,  136757, ...,  137349,  137351,  137353],
        [ 137354,  137356,  137358, ...,  137950,  137952,  137954],
    

In [49]:
matYF = matA[::,1::,::2]
matYF

array([[[  15952,   15954,   15956, ...,   16548,   16550,   16552],
        [  16553,   16555,   16557, ...,   17149,   17151,   17153],
        [  17154,   17156,   17158, ...,   17750,   17752,   17754],
        ...,
        [  74249,   74251,   74253, ...,   74845,   74847,   74849],
        [  74850,   74852,   74854, ...,   75446,   75448,   75450],
        [  75451,   75453,   75455, ...,   76047,   76049,   76051]],

       [[  76653,   76655,   76657, ...,   77249,   77251,   77253],
        [  77254,   77256,   77258, ...,   77850,   77852,   77854],
        [  77855,   77857,   77859, ...,   78451,   78453,   78455],
        ...,
        [ 134950,  134952,  134954, ...,  135546,  135548,  135550],
        [ 135551,  135553,  135555, ...,  136147,  136149,  136151],
        [ 136152,  136154,  136156, ...,  136748,  136750,  136752]],

       [[ 137354,  137356,  137358, ...,  137950,  137952,  137954],
        [ 137955,  137957,  137959, ...,  138551,  138553,  138555],
    

In [50]:
matPF = matA[::,::2,::2]
matPF

array([[[  15351,   15353,   15355, ...,   15947,   15949,   15951],
        [  16553,   16555,   16557, ...,   17149,   17151,   17153],
        [  17755,   17757,   17759, ...,   18351,   18353,   18355],
        ...,
        [  73047,   73049,   73051, ...,   73643,   73645,   73647],
        [  74249,   74251,   74253, ...,   74845,   74847,   74849],
        [  75451,   75453,   75455, ...,   76047,   76049,   76051]],

       [[  76052,   76054,   76056, ...,   76648,   76650,   76652],
        [  77254,   77256,   77258, ...,   77850,   77852,   77854],
        [  78456,   78458,   78460, ...,   79052,   79054,   79056],
        ...,
        [ 133748,  133750,  133752, ...,  134344,  134346,  134348],
        [ 134950,  134952,  134954, ...,  135546,  135548,  135550],
        [ 136152,  136154,  136156, ...,  136748,  136750,  136752]],

       [[ 136753,  136755,  136757, ...,  137349,  137351,  137353],
        [ 137955,  137957,  137959, ...,  138551,  138553,  138555],
    

In [51]:
matB = mat[:NxBase*NyBase]

In [52]:
matPI = np.append(matB,matPF[:-1:,::,::]).reshape(vZ,NyBase,NxBase)
matPI 

array([[[      0,       1,       2, ...,     298,     299,     300],
        [    301,     302,     303, ...,     599,     600,     601],
        [    602,     603,     604, ...,     900,     901,     902],
        ...,
        [  14448,   14449,   14450, ...,   14746,   14747,   14748],
        [  14749,   14750,   14751, ...,   15047,   15048,   15049],
        [  15050,   15051,   15052, ...,   15348,   15349,   15350]],

       [[  15351,   15353,   15355, ...,   15947,   15949,   15951],
        [  16553,   16555,   16557, ...,   17149,   17151,   17153],
        [  17755,   17757,   17759, ...,   18351,   18353,   18355],
        ...,
        [  73047,   73049,   73051, ...,   73643,   73645,   73647],
        [  74249,   74251,   74253, ...,   74845,   74847,   74849],
        [  75451,   75453,   75455, ...,   76047,   76049,   76051]],

       [[  76052,   76054,   76056, ...,   76648,   76650,   76652],
        [  77254,   77256,   77258, ...,   77850,   77852,   77854],
    